plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '5.1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = '0.2.0-1.19.2'
group = 'lv.sanelite.initium' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = 'initium'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {

    mappings channel: 'official', version: '1.19.2'

    runs {
        client {
            workingDirectory project.file('run')
            jvmArg "-XX:+AllowEnhancedClassRedefinition"
            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            property 'forge.enabledGameTestNamespaces', 'initium'

            mods {
                initium {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            property 'forge.enabledGameTestNamespaces', 'initium'

            mods {
                initium {
                    source sourceSets.main
                }
            }
        }

        gameTestServer {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            property 'forge.enabledGameTestNamespaces', 'initium'

            mods {
                initium {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            args '--mod', 'initium', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            mods {
                initium {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
    }
    maven {
        name = 'rhino-forge'
        url 'https://maven.saps.dev/releases'

    }
    maven {
        url 'https://libs.azuredoom.com:4443/mods'
    }

}


dependencies {

    minecraft 'net.minecraftforge:forge:1.19.2-43.3.2'
//    implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.19:3.1.40')
    implementation fg.deobf('dev.latvian.mods:rhino-forge:1902.2.2-build.272')
    implementation fg.deobf('mod.azure.azurelib:azurelib-forge-1.19.2:1.0.36')
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

}


jar {
    manifest {
        attributes([
                "Specification-Title"     : "initium",
                "Specification-Vendor"    : "initiumsareus",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "initiumsareus",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
